### ISSUE TITLE
Widget design meta issue.

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/quiz#196]
Umiddelbare tasks omkring design / usability af indlejret widget, - som videreudvikling af den  nuværende grundlæggende funktionalitet (implementeret via standard material design komponenter):

- [x] Knapper har farve (primær/sekundær for farvetemaet) #190 
- [x] Konfigurerbare primær/sekundær farve #190 
- [x] Start på design, - simpelt papir-udkast, samt vend planen med team'ets UX'er  #174 
- [ ] Topbar med titel skal være stylet som AppBar
- [ ] Bedre layout / spacing omkring knapper #189, #188 
- [ ] Billed/medie-elementer tilpasses bedre i størelse
- [ ] Typografi og formattinger(links/overskrifter/etc.) af tekstelementer
- [ ] Evt. konfigurerbar font (nu eller måske senere?)
- [ ] Evt. baggrundsbillede / baggrundsfarve (nu eller måske senere?)

Tilføjede tasks efter at vendt designet med vores UX'er:

- [ ] Hjælp-knap måske ikke som fuldbredde, så der er mere fokus på svar.
- [ ] Maks-bredde i indlejring, i.e. 960px eller lignende

Når første udgave af designet er implementeret:

- [ ] Konkret usability med brugere med konkret quiz, - og notér hvordan de interagere med løsningen og hvilke forbedringer dette peger i retning af.

Nice-to-have, hvis der er ekstra tid til finpudsning, når alt andet er kørende:

- [ ] Transitioner, højre til venstre når man gå igennem quiz, op/ned når man åbner/lukker hjælp.

**Comment by rasmuserik** [comment]
Duplicate of #60 - moved content / notes there.
