### ISSUE TITLE
Design for quiz-widget

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/quiz#60]
Umiddelbare tasks omkring design / usability af indlejret widget, - som videreudvikling af den  nuværende grundlæggende funktionalitet (implementeret via standard material design komponenter):

- [x] Knapper har farve (primær/sekundær for farvetemaet) #190 
- [x] Konfigurerbare primær/sekundær farve #190 
- [x] Start på design, - simpelt papir-udkast, samt vend planen med team'ets UX'er  #174 
- [x] Topbar med titel skal være stylet som AppBar
- [x] Bedre layout / spacing omkring knapper #189, #188 
- [x] Billed/medie-elementer tilpasses bedre i størelse
- [x] Typografi og formattinger(links/overskrifter/etc.) af tekstelementer
- [x]  Baggrundsbillede / baggrundsfarve (nu eller måske senere?)

Tilføjede tasks efter at vendt designet med vores UX'er:

- [ ] Hjælp-knap måske ikke som fuldbredde, så der er mere fokus på svar. #253
- [x] Maks-bredde i indlejring, i.e. 960px eller lignende

Når første udgave af designet er implementeret:

- [ ] Konkret usability med brugere med konkret quiz, - og notér hvordan de interagere med løsningen og hvilke forbedringer dette peger i retning af. #254

Nice-to-have, hvis der er ekstra tid til finpudsning, når alt andet er kørende:

- [ ] Transitioner, højre til venstre når man gå igennem quiz, op/ned når man åbner/lukker hjælp. #255

**Comment by rasmuserik** [comment]
Det initielle design er implementeret, - og har nu oprettet issues på øvrigt ting der ligger på backlog'en
